### ISSUE TITLE
Step7: Minor bug when toggling between currencies in history

### ISSUE THREAD

**Issue by mmerkes** [ionic-in-action/chapter5#1]
Here's the repro:
1. Checkout step7
2. Go to history tab
3. Select RUB
4. Select USD
5. Select RUB

At this point, the chart appears to have updated, but USD is still selected. Didn't investigate the cause of it and it's obviously very minor, but I thought I'd file a bug.

**Comment by mmerkes** [comment]
On further toying, the issue seems to come up whenever you go back to your previous currency.

**Comment by gnomeontherun** [comment]
A very awesome bug report, thanks. I'll dig into it, I have a few ideas what is happening.

**Comment by gnomeontherun** [comment]
So it has to do with Ionic cacheing views, and the way the select is setup.

History->USD - Load and cache view 1 (select is set to USD)
Change select to RUB - Changes the select in view 1 to display RUB, then loads and caches view 2 (select is then set to RUB)
Go back to USD - Reload cached view 1 (select was still changed to RUB, and will display even though chart uses currency code from URL param)

I can solve it by not caching the views (which is handy here) or changing the way models are used. Working through it.

**Comment by mmerkes** [comment]
That would have been my guess. When we upgraded to the latest Ionic, there were a ton of bugs introduced because of the caching...

**Comment by gnomeontherun** [comment]
Chose to solve by listening for the `$ionicView.beforeEnter` event. It provides a teachable moment to discuss the events and use cases, rather than just disabling the caching.

**Comment by mmerkes** [comment]
Smart choice. Disabling the cache would be avoiding the problem rather than dealing with it.
