### ISSUE TITLE
Currencies Service with local storage example

### ISSUE THREAD

**Issue by chadwhitaker** [ionic-in-action/chapter5#2]
Would you be able to provide a quick example on how to implement local storage with the Currencies Service? I understand how to set and retrieve from local storage, but I'm having trouble with including it with the service and accessing the updated data across the app entire.

Thanks, @gnomeontherun! Excellent book so far! :+1:

**Comment by chadwhitaker** [comment]
Just found my answer in Chapter 7.5 :)

I updated my Currencies Services to the following:

```
.factory('Currencies', function ($window) {
  var Currencies = {
    data: [],
    save: function (currencies) {
      $window.localStorage.setItem('currencies', angular.toJson(currencies));
    }
  };

  var defaultCurrencies = [
    { code: 'AUD', text: 'Australian Dollar', selected: true },
    { code: 'BRL', text: 'Brazilian Real', selected: false },
    { code: 'CAD', text: 'Canadian Dollar', selected: true },
    { code: 'CHF', text: 'Swiss Franc', selected: false },
    { code: 'CNY', text: 'Chinese Yuan', selected: true},
    { code: 'EUR', text: 'Euro', selected: true },
    { code: 'GBP', text: 'British Pound Sterling', selected: true },
    { code: 'IDR', text: 'Indonesian Rupiah', selected: false },
    { code: 'ILS', text: 'Israeli New Sheqel', selected: false },
    { code: 'MXN', text: 'Mexican Peso', selected: true },
    { code: 'NOK', text: 'Norwegian Krone', selected: false },
    { code: 'NZD', text: 'New Zealand Dollar', selected: false },
    { code: 'PLN', text: 'Polish Zloty', selected: false },
    { code: 'RON', text: 'Romanian Leu', selected: false },
    { code: 'RUB', text: 'Russian Ruble', selected: true },
    { code: 'SEK', text: 'Swedish Krona', selected: false },
    { code: 'SGD', text: 'Singapore Dollar', selected: false },
    { code: 'USD', text: 'United States Dollar', selected: true },
    { code: 'ZAR', text: 'South African Rand', selected: false }
  ];

  try {
    var items = angular.fromJson($window.localStorage.getItem('currencies')) || defaultCurrencies;
    Currencies.data = items;
  } catch(e) {
    Currencies.data = defaultCurrencies;
  }

  return Currencies;
});
```

I then updated the controllers to use `Currencies.data` and tweaked the currencies/settings controller to use `Currencies.save()` when making changes. I hope this helps others.

## 

@gnomeontherun I noticed from your website that you're located in Austin. Have you done any talks or meetups around Ionic yet?

**Comment by gnomeontherun** [comment]
Hey @chadwhitaker was working on a post to you but you have solved it. The main thing to consider is how to build it as a service (which you've done here). This is a good approach, and there are several ways to tackle this, depending on where you want the logic and the type of API you want the service to have.

Yes I'm in Austin, and am giving a talk at the November AngularJS meetup http://www.meetup.com/AngularJS/events/224925897/.

**Comment by chadwhitaker** [comment]
Awesome. I signed up and I'll try to make it.

**Comment by gnomeontherun** [comment]
Cool, be sure to introduce yourself!
