### ISSUE TITLE
Make sure the currency exists in the object before trying to access it

### ISSUE THREAD

**Issue by krio** [ionic-in-action/chapter5#3]
If the exchange does not return an object for a key we are expecting then some browsers will throw an exception. For example, the exchange is not currently returning results for "CHF". This was causing a TypeError and execution was stopped.

```
$scope.load = function () {
    $http.get('https://api.bitcoinaverage.com/ticker/all').success(function (tickers) {
      angular.forEach($scope.currencies, function (currency) {
        currency.ticker = tickers[currency.code];
        currency.ticker.timestamp = new Date(currency.ticker.timestamp);
      });
    }).finally(function () {
      $scope.$broadcast('scroll.refreshComplete');
    });
  };
```

Maybe something more like this:

```
if(tickers.hasOwnProperty(currency.code)) {
  currency.ticker = tickers[currency.code];
  currency.ticker.timestamp = new Date(currency.ticker.timestamp);
}
```

**Comment by gnomeontherun** [comment]
Thanks, this is a good catch for hardening. I don't know why the API changed, which is the danger of using live APIs like this. I'll report this to the Errata thread.

**Comment by ahuimanu** [comment]
This has to be manually changed at the moment, is it possible to update this repo to remove the Swiss Franc?

**Comment by gnomeontherun** [comment]
I went ahead and commented it out from the final version.
