### ISSUE TITLE
app.js currently causes crashes in application

### ISSUE THREAD

**Issue by jeffswearingen** [ionic-in-action/chapter5#4]
It appears that the bitcoinaverage api is no longer returning the NOK and the RON.  Therefore lines 74 and 77 of www/js/app.js should be commented out.

**Comment by gnomeontherun** [comment]
Thanks, fixed in https://github.com/ionic-in-action/chapter5/commit/7685682ab41b7cfbd4c4be1245895c24b83dbe4e!
