### ISSUE TITLE
bitcoinaverage API is deprecated

### ISSUE THREAD

**Issue by 404157386** [ionic-in-action/chapter5#5]
The old api url is invalid, should be changed to new address:
1.rate.js:
$http.get('https://apiv2.bitcoinaverage.com/ticker/all')

2. history.js:
$http.get('https://apiv2.bitcoinaverage.com/indices/global/history/BTC' + $scope.history.currency + '?period=monthly&format=csv')

**Comment by gnomeontherun** [comment]
Well that is unfortunate! It has been a lesson learned to rely on a third party for book content, so thank you for digging into this to find alternative options.

I've updated master with these fixes!
